services:
  db:
    image: postgres:16
    container_name: onebrief_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: freelancer_platform
    ports:
      - "5432:5432"
    volumes:
      - freelancer_platform_pgdata:/var/lib/postgresql/data

volumes:
  freelancer_platform_pgdata:

