import crypto from 'crypto';

/**
 * Generate a random token for client access links
 */
export function generateToken(): string {
  return crypto.randomBytes(16).toString('hex');
}

/**
 * Hash a token using SHA-256 for secure storage
 */
export function hashToken(token: string): string {
  return crypto.createHash('sha256').update(token).digest('hex');
}

/**
 * Normalize a token value coming from a URL to the value stored in DB.
 *
 * - If the URL already contains a 64-char sha256 hex token, use it directly.
 * - Otherwise, hash the token (for raw 32-char tokens generated by `generateToken()`).
 */
export function tokenToStoredValue(token: string): string {
  const trimmed = token.trim().toLowerCase();
  const isSha256Hex = /^[0-9a-f]{64}$/.test(trimmed);
  return isSha256Hex ? trimmed : hashToken(trimmed);
}

/**
 * Verify if a token matches the stored hash
 */
export function verifyToken(token: string, hash: string): boolean {
  return hashToken(token) === hash;
}

/**
 * Generate a URL-friendly slug from project title and client name
 */
export function generateProjectSlug(clientName: string, projectTitle: string): string {
  const combined = `${clientName}-${projectTitle}`;
  return combined
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .substring(0, 50);
}
